name:                pwnedk
version:             2.0.0
github:              "githubuser/pwnedk"
license:             GPL-3
author:              "Jörg K.-H. W. Brüggmann"
maintainer:          "info@joerg-brueggmann.de"
copyright:           "2023-2024 Jörg K.-H. W. Brüggmann"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pwnedk#readme>

dependencies:
- base >= 4.7 && < 5
- process
- bytestring
- cryptohash-sha1
- split
- echo
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pwnedk:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pwnedk

tests:
  pwnedk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pwnedk
